Repository AnguHashBlog/angular-material, pull requests merged in 2024-03, with the labels that each got.

#1 hashnode blog url changed to 'https://hashnode-blog.hashnodeng.com/'
  angular-material-app/src/app/graphql.operations.ts
Labels: enhancement

#25 readme update
  README.md
  anguhashblog.png
Labels: 📄 documentation, 🖼️ images & icons

#31 Update styles.scss
  angular-material-app/src/styles.scss
Labels: 🐛 bug, 🖼️ images & icons, 🎨 styling

#34 Users can now try AnguHashBlog with their own Hashnode Blog URL 👏
  angular-material-app/src/app/app.component.html
  angular-material-app/src/app/app.component.ts
  angular-material-app/src/app/components/footer/footer.component.html
  angular-material-app/src/app/components/footer/footer.component.ts
  angular-material-app/src/app/components/header/header.component.html
  angular-material-app/src/app/components/header/header.component.scss
  angular-material-app/src/app/components/header/header.component.ts
  angular-material-app/src/app/components/layout/layout.component.html
  angular-material-app/src/app/components/layout/layout.component.ts
  angular-material-app/src/app/components/post-details/post-details.component.html
  angular-material-app/src/app/components/post-details/post-details.component.ts
  angular-material-app/src/app/components/posts/posts.component.ts
  angular-material-app/src/app/components/series/series.component.ts
  angular-material-app/src/app/graphql.operations.ts
  angular-material-app/src/app/partials/follow-dialog/follow-dialog.component.html
  angular-material-app/src/app/partials/follow-dialog/follow-dialog.component.ts
  angular-material-app/src/app/partials/search-dialog/search-dialog.component.ts
  angular-material-app/src/app/partials/settings-dialog/settings-dialog.component.html
  angular-material-app/src/app/partials/settings-dialog/settings-dialog.component.scss
  angular-material-app/src/app/partials/settings-dialog/settings-dialog.component.spec.ts
  angular-material-app/src/app/partials/settings-dialog/settings-dialog.component.ts
  angular-material-app/src/app/services/blog.service.ts
  angular-material-app/src/theme.scss
Labels: 🌟feature, 🛰️ apollo angular, GraphGL, RxJS, 🎨 styling, 📁 file structure

#39 feat(domsanitizer): using the native angular pipe
  angular-material-app/src/app/components/post-details/post-details.component.html
  angular-material-app/src/app/components/post-details/post-details.component.ts
Labels: 🌟feature, 🔒 security

#41 features and fixes multiple issues see PR details
  angular-material-app/src/app/components/blog-social-icons/blog-social-icons.component.html
  angular-material-app/src/app/components/blog-social-icons/blog-social-icons.component.scss
  angular-material-app/src/app/components/blog-social-icons/blog-social-icons.component.spec.ts
  angular-material-app/src/app/components/blog-social-icons/blog-social-icons.component.ts
  angular-material-app/src/app/components/header/header.component.html
  angular-material-app/src/app/components/header/header.component.scss
  angular-material-app/src/app/components/header/header.component.ts
  angular-material-app/src/app/components/post-details/post-details.component.html
  angular-material-app/src/app/components/post-details/post-details.component.scss
  angular-material-app/src/app/components/post-details/post-details.component.ts
  angular-material-app/src/app/components/posts/posts.component.html
  angular-material-app/src/app/components/posts/posts.component.ts
  angular-material-app/src/app/directives/youtube-video-embed.directive.spec.ts
  angular-material-app/src/app/directives/youtube-video-embed.directive.ts
  angular-material-app/src/app/graphql.operations.ts
  angular-material-app/src/app/models/post.ts
  angular-material-app/src/app/pipes/sanitizer-html.pipe.spec.ts
  angular-material-app/src/app/pipes/sanitizer-html.pipe.ts
  angular-material-app/src/assets/fontawesome/js/all.js
  angular-material-app/src/assets/fontawesome/js/all.min.js
  angular-material-app/src/assets/fontawesome/js/brands.js
  angular-material-app/src/assets/fontawesome/js/brands.min.js
  angular-material-app/src/assets/fontawesome/js/conflict-detection.js
  angular-material-app/src/assets/fontawesome/js/conflict-detection.min.js
  angular-material-app/src/assets/fontawesome/js/fontawesome.js
  angular-material-app/src/assets/fontawesome/js/fontawesome.min.js
  angular-material-app/src/assets/fontawesome/js/regular.js
  angular-material-app/src/assets/fontawesome/js/regular.min.js
  angular-material-app/src/assets/fontawesome/js/solid.js
  angular-material-app/src/assets/fontawesome/js/solid.min.js
  angular-material-app/src/assets/fontawesome/js/v4-shims.js
  angular-material-app/src/assets/fontawesome/js/v4-shims.min.js
  angular-material-app/src/assets/icons/dailydev.svg
  angular-material-app/src/assets/icons/facebook.svg
  angular-material-app/src/assets/icons/github.svg
  angular-material-app/src/assets/icons/hashnode.svg
  angular-material-app/src/assets/icons/instagram.svg
  angular-material-app/src/assets/icons/linkedin.svg
  angular-material-app/src/assets/icons/mastodon.svg
  angular-material-app/src/assets/icons/stackoverflow.svg
  angular-material-app/src/assets/icons/twitter.svg
  angular-material-app/src/assets/icons/website.svg
  angular-material-app/src/assets/icons/youtube.svg
  angular-material-app/src/index.html
Labels: 🐛 bug, 🌟feature, 🖼️ images & icons, 🔀 routing, 🎨 styling, 📁 file structure, custom directive

#44 feat(routing): the 'post' part is removed from post details path
  angular-material-app/src/app/app.routes.ts
  angular-material-app/src/app/components/header/header.component.html
  angular-material-app/src/app/components/posts/posts.component.html
  angular-material-app/src/app/components/posts/posts.component.ts
  angular-material-app/src/app/components/series/series.component.html
Labels: 🌟feature, 🔀 routing

#47 feat(layout, routing): layout and routing have been adjusted
  angular-material-app/src/app/app.component.html
  angular-material-app/src/app/app.component.scss
  angular-material-app/src/app/app.component.ts
  angular-material-app/src/app/app.routes.ts
  angular-material-app/src/app/components/footer/footer.component.html
  angular-material-app/src/app/components/footer/footer.component.ts
  angular-material-app/src/app/components/header/header.component.html
  angular-material-app/src/app/components/header/header.component.ts
  angular-material-app/src/app/components/layout/layout.component.html
  angular-material-app/src/app/components/layout/layout.component.scss
  angular-material-app/src/app/components/layout/layout.component.spec.ts
  angular-material-app/src/app/components/layout/layout.component.ts
  angular-material-app/src/app/components/post-details/post-details.component.html
  angular-material-app/src/app/components/post-details/post-details.component.scss
  angular-material-app/src/app/components/post-details/post-details.component.ts
  angular-material-app/src/app/components/posts/posts.component.scss
  angular-material-app/src/app/components/series/series.component.ts
  angular-material-app/src/styles.scss
Labels: 🌟feature, 🔀 routing, 🎨 styling, 📁 file structure

#48 feat(docs): issue templates yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: 📄 documentation

#50 redirect added and 'post/' reurned
  angular-material-app/src/app/app.routes.ts
  angular-material-app/src/app/components/posts/posts.component.html
  angular-material-app/src/app/components/series/series.component.html
Labels: 🐛 bug

#52 feat(docs): changelog
  angular-material-app/CHANGELOG.md
Labels: 📄 documentation

#53 docs(templates): issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: 📄 documentation

#56 feat(sitewide): initial responsivness mobile media query
  angular-material-app/src/app/components/header/header.component.html
  angular-material-app/src/app/components/header/header.component.scss
  angular-material-app/src/app/components/post-details/post-details.component.scss
  angular-material-app/src/app/components/posts/posts.component.scss
  angular-material-app/src/app/components/series/series.component.scss
  angular-material-app/src/app/partials/follow-dialog/follow-dialog.component.scss
  angular-material-app/src/app/partials/search-dialog/search-dialog.component.scss
  angular-material-app/src/app/partials/settings-dialog/settings-dialog.component.scss
  angular-material-app/src/styles.scss
Labels: 🌟feature, 📱responsiveness, 🎨 styling

#58 formatting
  angular-material-app/src/app/components/header/header.component.scss
Labels: 🎨 styling, core team work
