Repository AnguHashBlog/angular-material, pull requests merged in 2024-04, with the labels that each got.

#62 docs(contributing.md): more updates
  CONTRIBUTING.md
Labels: 📄 documentation, core team work

#61 feat(post-details): scroll to top
  angular-material-app/src/app/components/post-details/post-details.component.ts
Labels: 🌟feature, 🔄 ready to merge

#63 feat(post-details): file structure adjustments
  angular-material-app/src/app/components/post-details/post-details.component.ts
Labels: 📁 file structure, core team work

#65 docs(contributing.md): update and issue tracker links
  CONTRIBUTING.md
Labels: 📄 documentation, core team work

#67 feat(blog-social-icons)?: moved to partials folder
  angular-material-app/src/app/components/header/header.component.ts
  angular-material-app/src/app/components/post-details/post-details.component.ts
  angular-material-app/src/app/partials/blog-social-icons/blog-social-icons.component.html
  angular-material-app/src/app/partials/blog-social-icons/blog-social-icons.component.scss
  angular-material-app/src/app/partials/blog-social-icons/blog-social-icons.component.spec.ts
  angular-material-app/src/app/partials/blog-social-icons/blog-social-icons.component.ts
Labels: 🌟feature, 📁 file structure, core team work
